### ISSUE TITLE
You've stolen my code

### ISSUE THREAD

**Issue by rhubarbdog** [vittascience/microbit-libraries#8]
hi
your file `dht11.py` is an edit of my code at https://github.com/rhubarbdog/microbit-dht11
This is in breach on my License
please remove this code or contact me

**Comment by rhubarbdog** [comment]
it would also appear that the code `tm1637.py` has been stolen from either https://github.com/microbit-tm1637 or @mcauser

**Comment by mcauser** [comment]
Yep, it looks that way.
https://github.com/mcauser/microbit-tm1637/blob/master/tm1637.py
https://github.com/mcauser/microbit-my9221/blob/master/my9221.py

Both of mine are MIT licensed.
https://fossa.com/blog/open-source-licenses-101-mit-license/

> The MIT License requires two things in your copy and/or modification of the code:
> 1. The original copyright notice
> 2. A copy of the license itself

Be sure to include the original copyright notice in any MIT licensed code you find any copy.
A link back to the original author's code is also appreciated, but not a requirement.

**Comment by leomlr** [comment]
Hi Phil Hall, hi Mike Causer,

Sorry for using your libraries without its licenses and the link back to the original author's code. I changed that.
Thank you both, so much, for your work on microbit libraries.
